# Generated by Django 4.0.3 on 2023-03-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
