# Generated by Django 4.0.3 on 2023-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
