# Generated by Django 4.0.3 on 2023-03-27 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0006_alter_lead_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(blank=True, max_length=500, null=True)),
                ('myrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insaurance.usermappingrequest')),
            ],
        ),
    ]
