# Generated by Django 4.0.3 on 2023-03-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0007_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='image',
            new_name='invoice_image',
        ),
        migrations.AddField(
            model_name='lead',
            name='aadharcardb_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadharcardb_image'),
        ),
        migrations.AddField(
            model_name='lead',
            name='aadharcardf_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadharcardf_image'),
        ),
        migrations.AddField(
            model_name='lead',
            name='otherkyc_image',
            field=models.ImageField(blank=True, null=True, upload_to='other_image'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='pan_image'),
        ),
    ]
