# Generated by Django 4.0.3 on 2023-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0008_rename_image_lead_invoice_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='new_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='old_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
