# Generated by Django 4.0.3 on 2023-03-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0009_ticket_new_value_ticket_old_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='aadharcardb_image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_form'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='aadharcardf_image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_form'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='otherkyc_image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_form'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='lead_form'),
        ),
    ]
