# Generated by Django 4.0.3 on 2023-03-31 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0010_alter_lead_aadharcardb_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mylead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insaurance.lead'),
        ),
    ]
