# Generated by Django 4.0.3 on 2023-03-31 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0011_ticket_mylead'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(blank=True, max_length=500, null=True)),
                ('old_value', models.CharField(blank=True, max_length=200, null=True)),
                ('new_value', models.CharField(blank=True, max_length=200, null=True)),
                ('mylead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insaurance.lead')),
            ],
        ),
    ]
