# Generated by Django 4.0.3 on 2023-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0012_leadticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermappingrequest',
            name='renew_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
