# Generated by Django 4.0.3 on 2023-04-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insaurance', '0016_alter_usermappingrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermappingrequest',
            name='renew_at',
        ),
    ]
